my_list = [1 ,2, 3]
print(my_list)
my_list.insert(len(my_list), 6)
print(my_list)
my_list.insert(-1, 10)
print(my_list)
my_list.insert(0, 100)
print(my_list)
my_list.insert(100, 10000)
print(my_list)
print(len(my_list))
# print(my_list[100])